TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b

PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io/graphql
PDL_SCOPE: prod-fss.pdl.pdl-api

NOM_BASE_URL: https://nom-api.intern.nav.no/graphql
NOM_SCOPE: prod-gcp.nom.nom-api

SETTINGS_CLEANUP_CRON: 0 30 14 * * MON

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false