TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
PDL_SCOPE: dev-fss.pdl.pdl-api

NOM_BASE_URL: https://nom-api.intern.dev.nav.no/graphql
NOM_SCOPE: dev-gcp.nom.nom-api

SETTINGS_CLEANUP_CRON: 0 0 12 * * MON

spring:
  datasource:
    hikari:
      maximum-pool-size: 5

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true